# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: settings_reset
    artifact: reset
  - board: nice_nano_v2
    shield: sofle_left
    artifact: sofle_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: sofle_right
    artifact: sofle_right

  - board: nice_nano_v2
    shield: corne_left
    snippet: studio-rpc-usb-uart
    artifact: corne_left
    #
  - board: nice_nano_v2
    shield: corne_dongle  dongle_display
    snippet: studio-rpc-usb-uart
    artifact: corne_dongle

  - board: nice_nano_v2
    shield: corne_ph_left nice_view_adapter nice_view
    artifact: corne_ph_left

  - board: nice_nano_v2
    shield: corne_right  nice_view_adapter nice_view
    artifact: corne_right
