manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: kevinpastor
      url-base: https://github.com/kevinpastor
    - name: m165437
      url-base: https://github.com/M165437
    - name: s6t
      url-base: https://github.com/s6t
    - name: infely
      url-base: https://github.com/infely
    - name: urob
      url-base: https://github.com/urob
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: hitsmaxft
      url-base: https://github.com/hitsmaxft
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      clone-depth: 1
      import: app/west.yml
      path: zmodules/zmk
    - name: hammerbeam-slideshow
      remote: gpeye
      revision: main
      path: zmodules/hammerbeam-slideshow
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
      path: zmodules/zmk-nice-oled
    - name: nice-view-elemental
      remote: kevinpastor
      revision: main
      path: zmodules/nice-view-elemental
    - name: nice-view-gem
      remote: m165437
      revision: main
      path: zmodules/nice-view-gem
    - name: zmk-shield-nice-view-cats
      remote: s6t
      revision: main
      path: zmodules/zmk-shield-nice-view-cats
    - name: nice-view-battery
      remote: infely
      revision: main
      path: zmodules/nice-view-battery
    - name: zmk-helpers
      remote: urob
      revision: main
      path: zmodules/zmk-helpers
    - name: zmk-feature-status-led
      remote: hitsmaxft
      revision: main
  self:
    path: config
