manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hitsmaxft
      url-base: https://github.com/hitsmaxft
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      clone-depth: 1
      import:
        path-prefix: zmk_exts
        file: app/west.yml
  self:
    path: config
    import:
      file: deps.yml
      path-prefix: zmk_exts
